Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/07/2024
Var
// Seção de Declarações das variáveis 
Inicial, final, duracao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a hora inicial: ")
leia(Inicial)

Fimalgoritmo